# This is a config for E2B sandbox template.
# You can use template ID (rxf77u9vgczuwtuj2i25) or template name (techship-vibe-nextjs-test-2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("techship-vibe-nextjs-test-2") # Sync sandbox
# sandbox = await AsyncSandbox.create("techship-vibe-nextjs-test-2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('techship-vibe-nextjs-test-2')

team_id = "a3480bf3-811c-47eb-86b2-2e41750f75cb"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "techship-vibe-nextjs-test-2"
template_id = "rxf77u9vgczuwtuj2i25"
