import {
  AlertTriangle,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ConciergeBell,
  Copy,
  CreditCard,
  Edit,
  File,
  FileText,
  FolderTree,
  Github,
  Image,
  ImagePlus,
  Loader2,
  MoreHorizontal,
  MoreVertical,
  Orbit,
  Plus,
  PlusCircle,
  Rocket,
  Server,
  Settings,
  Trash,
  User,
  X,
  type LucideIcon,
} from "lucide-react"

export type Icon = LucideIcon

export const Icons = {
  logo: Rocket,
  close: X,
  copy: Copy,
  bell: ConciergeBell,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronDown: ChevronDown,
  edit: Edit,
  github: Github,
  spinner: Loader2,
  post: FileText,
  page: File,
  media: Image,
  mediaPlus: ImagePlus,
  settings: Settings,
  user: User,
  add: Plus,
  plusCircle: PlusCircle,
  warning: AlertTriangle,
  moreHorizontal: MoreHorizontal,
  ellipsis: MoreVertical,
  trash: Trash,
  tree: FolderTree,
  billing: CreditCard,
  server: Server,
  space: Orbit,
  check: Check,
}
